version: "3.8"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      PORT: 8080
      DB_TYPE: "postgres"
      DB_USER: "postgres" 
      DB_PASSWORD: "postgres"
      DB_DATABASE: "postgres"
      DB_PORT: "5432"
      DB_HOST: "db"
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "postgres"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

