name: Manual AWS Deployment

on:
  workflow_dispatch:
    inputs:
      awsCredentials:
        description: 'AWS Credentials'
        required: true

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - uses: levibostian/action-hide-sensitive-inputs@v1
    - name: Deploy to AWS
      run: |
        echo "${{ github.event.inputs.awsCredentials }}" | tr " " "\n" > credentials
        export $(cat credentials.txt | xargs)
        echo "$(cat credentials.txt)"
        rm credentials.txt
        terraform init
        terraform apply -auto-approve
