name: Manual AWS Deployment

on:
  workflow_dispatch:
    inputs:
      awsCredentials:
        description: 'AWS Credentials'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Mask sensitive inputs
      uses: levibostian/action-hide-sensitive-inputs@v1

    - name: Set AWS Credentials as Environment Variables and Save to File
      run: |
        echo "$AWS_CREDENTIALS" > credentials.txt
        export AWS_ACCESS_KEY_ID=$(grep -oP '(?<=AWS_ACCESS_KEY_ID=)\S+' credentials.txt)
        export AWS_SECRET_ACCESS_KEY=$(grep -oP '(?<=AWS_SECRET_ACCESS_KEY=)\S+' credentials.txt)
        export AWS_SESSION_TOKEN=$(grep -oP '(?<=AWS_SESSION_TOKEN=)\S+' credentials.txt)

    - name: Deploy to AWS
      run: |
        terraform init
        terraform apply -auto-approve
