name: Manual AWS Teardown

on:
  workflow_dispatch:
    inputs:
      awsCredentials:
        description: 'AWS Credentials'
        required: true

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        
    - name: Teardown to AWS
      run: |
        echo "${{ github.event.inputs.awsCredentials }}" > credentials.txt
        export $(cat credentials.txt | xargs)
        rm credentials.txt
        ./teardown.sh