name: Manual AWS Teardown

on:
  workflow_dispatch:
    inputs:
      awsCredentials:
        description: 'AWS Credentials'
        required: true

jobs:
  Teardown:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        
    - name: Teardown to AWS
      run: |
          echo "::set-env name=AWS_CREDENTIALS::${{ github.event.inputs.awsCredentials }}"
          export AWS_ACCESS_KEY_ID=$(grep -oP '(?<=AWS_ACCESS_KEY_ID=)\S+' credentials.txt)
          export AWS_SECRET_ACCESS_KEY=$(grep -oP '(?<=AWS_SECRET_ACCESS_KEY=)\S+' credentials.txt)
          export AWS_SESSION_TOKEN=$(grep -oP '(?<=AWS_SESSION_TOKEN=)\S+' credentials.txt)
          echo "::add-mask::$AWS_ACCESS_KEY_ID" >/dev/null
          echo "::add-mask::$AWS_SECRET_ACCESS_KEY" >/dev/null
          echo "::add-mask::$AWS_SESSION_TOKEN" >/dev/null
          rm credentials.txt
          terraform init
          terraform destroy -auto-approve
