name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    # Install Node.js and cache dependencies
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Run backend build and test
    - name: Build and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      working-directory: backend

  integration_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run integration tests
      run: |
        chmod +x ./integration_tests/tests.sh
        ./integration_tests/tests.sh